// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Album struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ArtistID  uuid.UUID
}

type ArtistsSong struct {
	ArtistID uuid.UUID
	SongID   uuid.UUID
}

type Like struct {
	UserID uuid.UUID
	SongID uuid.UUID
}

type Playlist struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	OwnerID   uuid.UUID
}

type PlaylistsSong struct {
	PlaylistID uuid.UUID
	SongID     uuid.UUID
}

type Song struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	AlbumID   uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
	Password  string
	IsArtist  bool
}
