// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: playlists.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPlayList = `-- name: CreatePlayList :one
INSERT INTO playlists (id, created_at, updated_at, name, owner_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, owner_id
`

type CreatePlayListParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	OwnerID   uuid.UUID
}

func (q *Queries) CreatePlayList(ctx context.Context, arg CreatePlayListParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, createPlayList,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.OwnerID,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
	)
	return i, err
}
